version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 201652008/express-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: 201652008/express-backend:latest
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 